[package]
name = "mhcast"
version = "0.1.0"
edition = "2021"
authors = ["myl7 <myl@myl.moe>"]

[dependencies]
aes = "0.8.4"
bitvec = "1.0.1"
ctr = "0.9.2"
ff = "0.13.0"
fss-rs = { path = "../fss" }
group = "0.13.0"
jubjub = "0.10.0"
num = "0.4.3"
prost = "0.13.1"
rand = { version = "0.8.5", features = ["std", "std_rng"] }
rayon = "1.10.0"
sha2 = "0.10.8"
tonic = "0.12.1"
verenc = "0.2.0"

[dev-dependencies]
arbtest = "0.3.1"

[build-dependencies]
tonic-build = "0.12.1"
