[package]
name = "mhcast"
version = "0.1.0"
edition = "2021"
authors = ["myl7 <myl@myl.moe>"]

[dependencies]
bitvec = "1.0.1"
fss-rs = { path = "../fss" }
group = "0.13.0"
jubjub = "0.10.0"
num = "0.4.3"
rand = { version = "0.8.5", features = ["std", "std_rng"] }
rayon = "1.10.0"
sha2 = "0.10.8"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
arbtest = "0.3.1"
