// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: mhcast.proto

package mhcast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	S0            []byte                 `protobuf:"bytes,2,opt,name=s0,proto3" json:"s0,omitempty"`
	CwsL          []byte                 `protobuf:"bytes,3,opt,name=cws_l,json=cwsL,proto3" json:"cws_l,omitempty"`
	CwNp1L        []byte                 `protobuf:"bytes,4,opt,name=cw_np1_l,json=cwNp1L,proto3" json:"cw_np1_l,omitempty"`
	CwsR          []byte                 `protobuf:"bytes,5,opt,name=cws_r,json=cwsR,proto3" json:"cws_r,omitempty"`
	CwNp1R        []byte                 `protobuf:"bytes,6,opt,name=cw_np1_r,json=cwNp1R,proto3" json:"cw_np1_r,omitempty"`
	Pm            []byte                 `protobuf:"bytes,7,opt,name=pm,proto3" json:"pm,omitempty"`
	T             []byte                 `protobuf:"bytes,8,opt,name=t,proto3" json:"t,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_mhcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_mhcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_mhcast_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Msg) GetS0() []byte {
	if x != nil {
		return x.S0
	}
	return nil
}

func (x *Msg) GetCwsL() []byte {
	if x != nil {
		return x.CwsL
	}
	return nil
}

func (x *Msg) GetCwNp1L() []byte {
	if x != nil {
		return x.CwNp1L
	}
	return nil
}

func (x *Msg) GetCwsR() []byte {
	if x != nil {
		return x.CwsR
	}
	return nil
}

func (x *Msg) GetCwNp1R() []byte {
	if x != nil {
		return x.CwNp1R
	}
	return nil
}

func (x *Msg) GetPm() []byte {
	if x != nil {
		return x.Pm
	}
	return nil
}

func (x *Msg) GetT() []byte {
	if x != nil {
		return x.T
	}
	return nil
}

type WriteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           int32                  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResp) Reset() {
	*x = WriteResp{}
	mi := &file_mhcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResp) ProtoMessage() {}

func (x *WriteResp) ProtoReflect() protoreflect.Message {
	mi := &file_mhcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResp.ProtoReflect.Descriptor instead.
func (*WriteResp) Descriptor() ([]byte, []int) {
	return file_mhcast_proto_rawDescGZIP(), []int{1}
}

func (x *WriteResp) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

type Commit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Beta          []byte                 `protobuf:"bytes,2,opt,name=beta,proto3" json:"beta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Commit) Reset() {
	*x = Commit{}
	mi := &file_mhcast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Commit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Commit) ProtoMessage() {}

func (x *Commit) ProtoReflect() protoreflect.Message {
	mi := &file_mhcast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Commit.ProtoReflect.Descriptor instead.
func (*Commit) Descriptor() ([]byte, []int) {
	return file_mhcast_proto_rawDescGZIP(), []int{2}
}

func (x *Commit) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Commit) GetBeta() []byte {
	if x != nil {
		return x.Beta
	}
	return nil
}

type CommitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitResp) Reset() {
	*x = CommitResp{}
	mi := &file_mhcast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResp) ProtoMessage() {}

func (x *CommitResp) ProtoReflect() protoreflect.Message {
	mi := &file_mhcast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResp.ProtoReflect.Descriptor instead.
func (*CommitResp) Descriptor() ([]byte, []int) {
	return file_mhcast_proto_rawDescGZIP(), []int{3}
}

var File_mhcast_proto protoreflect.FileDescriptor

const file_mhcast_proto_rawDesc = "" +
	"\n" +
	"\fmhcast.proto\x12\x06mhcast\"\xa1\x01\n" +
	"\x03Msg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x0e\n" +
	"\x02s0\x18\x02 \x01(\fR\x02s0\x12\x13\n" +
	"\x05cws_l\x18\x03 \x01(\fR\x04cwsL\x12\x18\n" +
	"\bcw_np1_l\x18\x04 \x01(\fR\x06cwNp1L\x12\x13\n" +
	"\x05cws_r\x18\x05 \x01(\fR\x04cwsR\x12\x18\n" +
	"\bcw_np1_r\x18\x06 \x01(\fR\x06cwNp1R\x12\x0e\n" +
	"\x02pm\x18\a \x01(\fR\x02pm\x12\f\n" +
	"\x01t\x18\b \x01(\fR\x01t\"\x1d\n" +
	"\tWriteResp\x12\x10\n" +
	"\x03ret\x18\x01 \x01(\x05R\x03ret\",\n" +
	"\x06Commit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04beta\x18\x02 \x01(\fR\x04beta\"\f\n" +
	"\n" +
	"CommitResp2d\n" +
	"\x06Mhcast\x12'\n" +
	"\x05Write\x12\v.mhcast.Msg\x1a\x11.mhcast.WriteResp\x121\n" +
	"\vShareCommit\x12\x0e.mhcast.Commit\x1a\x12.mhcast.CommitRespB\x18Z\x16github.com/myl7/mhcastb\x06proto3"

var (
	file_mhcast_proto_rawDescOnce sync.Once
	file_mhcast_proto_rawDescData []byte
)

func file_mhcast_proto_rawDescGZIP() []byte {
	file_mhcast_proto_rawDescOnce.Do(func() {
		file_mhcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mhcast_proto_rawDesc), len(file_mhcast_proto_rawDesc)))
	})
	return file_mhcast_proto_rawDescData
}

var file_mhcast_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mhcast_proto_goTypes = []any{
	(*Msg)(nil),        // 0: mhcast.Msg
	(*WriteResp)(nil),  // 1: mhcast.WriteResp
	(*Commit)(nil),     // 2: mhcast.Commit
	(*CommitResp)(nil), // 3: mhcast.CommitResp
}
var file_mhcast_proto_depIdxs = []int32{
	0, // 0: mhcast.Mhcast.Write:input_type -> mhcast.Msg
	2, // 1: mhcast.Mhcast.ShareCommit:input_type -> mhcast.Commit
	1, // 2: mhcast.Mhcast.Write:output_type -> mhcast.WriteResp
	3, // 3: mhcast.Mhcast.ShareCommit:output_type -> mhcast.CommitResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mhcast_proto_init() }
func file_mhcast_proto_init() {
	if File_mhcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mhcast_proto_rawDesc), len(file_mhcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mhcast_proto_goTypes,
		DependencyIndexes: file_mhcast_proto_depIdxs,
		MessageInfos:      file_mhcast_proto_msgTypes,
	}.Build()
	File_mhcast_proto = out.File
	file_mhcast_proto_goTypes = nil
	file_mhcast_proto_depIdxs = nil
}
