[tool.poetry]
name = "mhcast"
version = "0.1.0"
description = ""
authors = ["myl7 <myl@myl.moe>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10" # For the | operator in type hints
matplotlib = "^3.9.2"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
mypy = "^1.11.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.mypy]
